### ISSUE TITLE
Plugin not working with german special chars

### ISSUE THREAD

**Issue by patric-eberle** [soderlind/wp-anchor-header#1]
I use your plugin on a wordpress installation with german text. Unfortunately after activating it all ä, ö, ü charachters are replaced with non readable text (also outside of h1-h6 tags).

WP 4.2.2
Plugin 0.1.7
Selfhosting

http://wiki.derverstaerker.ch/sass-einleitung/
![bildschirmfoto 2015-06-17 um 17 13 18](https://cloud.githubusercontent.com/assets/10571945/8210995/f9f85b10-1514-11e5-91e9-94659f2378e2.png)

**Comment by soderlind** [comment]
Thank you, I guess I'd seen this if my site was in Norwegian. I'll have a look and hopefully it's a simple fix.

**Comment by soderlind** [comment]
.. btw, I can reproduce the error

**Comment by soderlind** [comment]
The issue was easy to fix https://github.com/soderlind/wp-anchor-header/blob/master/wp-anchor-header.php#L66

**Comment by patric-eberle** [comment]
Works now as expected. Thank you for the useful plugin!
