### ISSUE TITLE
Deactivate anchor-links on specific pages

### ISSUE THREAD

**Issue by selimovd** [soderlind/wp-anchor-header#5]
Hello,

first of all thank you for that plugin, I really love it and it works very well!
I was wondering, is it possible to disable the creation of the anchor links on specific pages? I have one specific page where the content changes quite often, so the links will not work in the future. Is it possible to deactivate it for a specific page?

Otherwise, is it possible to only activate it for the posts?

Thank you and best regards

**Comment by soderlind** [comment]
Hi @selimovd, glad you like it.

You can disable the anchorlinks on a specific post/page, using CSS.

1) On the page you want to disable it, view source and in the `body` tag, find the `postid-X` / `page-id-X` class, eg  `<body class="page-id-2">`

2) In WP Admin, Appearance->Customize->Additional CSS, add the following:

```css
.page-id-2 a.anchorlink {
	display:none;
}
```

**Comment by selimovd** [comment]
Thank you so much @soderlind , that did it!
Thanks again for that great plugin, I really enjoy it and best regards
